### ISSUE TITLE
Update for Processing 3.0?

### ISSUE THREAD

**Issue by CyrusSUEN** [apitaru/sonia#1]
I would like to know if there are any plans to update your Sonia library for Processing 3.0.
Thank you!

**Comment by apitaru** [comment]
Unfortunately the core library that Sonia is based on (
http://www.softsynth.com/jsyn/) has changed dramatically and I won't be
available to re-jig it to Processing-3 anytime soon.

Amit

**Comment by CyrusSUEN** [comment]
Thanks!

**Comment by apitaru** [comment]
There's a new PR for Processing 3 that I've just merged in. Not sure if its 100% compatible but worth taking a look if you're up for it.

Cheers, 
Amit

**Comment by dhowe** [comment]
Please note that this has thus far only been tested on the Mac (in Processing 2.2x, 3.01, and Eclipse)...

**Comment by CyrusSUEN** [comment]
> only been tested on the Mac (in Processing 2.2x, 3.01, and Eclipse)

I've tested [it](https://github.com/dhowe/sonia/raw/master/Sonia.zip) on Windows 10 with Processing 3. No problem running the included 3 example pde at all.
